spring:
  datasource:
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
    url: jdbc:mysql://${RDS_HOSTNAME:13.94.132.138}:${RDS_PORT:3312}/${RDS_DB_NAME:keycloak}?serverTimezone=UTC
    username: ${RDS_USERNAME:keycloak}
    password: ${RDS_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

keycloak:
  resource: auth-service
  credentials: 
    secret: 4d19c603-89f7-4de3-abc4-ece1ba86818f
    
keycloak-admin-user: admin
keycloak-admin-password: admin
#  use-resource-role-mappings: true

server:
  port: 5000