spring:
  datasource:
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:cloudoeedb}?serverTimezone=UTC
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

keycloak:
  resource: confirmation-service
  credentials: 
    secret: 617fee7f-066d-43c1-b7c3-75fd81792b5e
#  use-resource-role-mappings: true
     
server:
  port: 8050