spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://localhost:5000}
          predicates:
            - Path=/auth/**
        - id: maindata-service
            uri: ${MAINDATA_SERVICE_URI:http://localhost:8090}
            predicates:
              - Path=/main-data/**
        - id: stock-service
            uri: ${STOCK_SERVICE_URI:http://localhost:8070}
            predicates:
              - Path=/stock/**
        - id: order-service
            uri: ${ORDER_SERVICE_URI:http://localhost:8060}
            predicates:
              - Path=/order/**
        - id: confirmation-service
            uri: ${CONFIRMATION_SERVICE_URI:http://localhost:8050}
            predicates:
              - Path=/auth/**
        - id: auth-service
            uri: ${AUTH_SERVICE_URI:http://localhost:5000}
            predicates:
              - Path=/confirmation/**
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
#ribbon:
#  ReadTimeout: 20000
#  ConnectTimeout: 20000

#zuul:
#  sensitiveHeaders: Cookie,Set-Cookie
#  ignoredServices: '*'
#  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
#  host:
#    connect-timeout-millis: 60000
#    socket-timeout-millis: 60000
#    max-total-connections: 200
#    max-per-route-connections: 20
#    time-unit: MILLISECONDS
#    time-to-live: 10000
  #host:
   #  connect-timeout-millis: 20000
    # socket-timeout-millis: 20000

#  
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
#    
  
#  routes:
#      auth-service:
#          service-id: auth-service
#          path: /auth/**
#          url: ${AUTH_SERVICE_URI:http://localhost:5000}
#          stripPrefix: false
#          sensitiveHeaders: Cookie,Set-Cookie
#      maindata-service:
#          service-id: maindata-service
#          path: /main-data/**
#          url: ${MAINDATA_SERVICE_URI:http://localhost:8090}
#          stripPrefix: false
#          sensitiveHeaders: Cookie,Set-Cookie
#      stock-service:
#          service-id: stock-service
#          path: /stock/**
#          url: ${STOCK_SERVICE_URI:http://localhost:8070}
#          stripPrefix: false
#          sensitiveHeaders: Cookie,Set-Cookie
#      order-service:
#          service-id: order-service
#          path: /order/**
#          url: ${ORDER_SERVICE_URI:http://localhost:8060}
#          stripPrefix: false
#          sensitiveHeaders: Cookie,Set-Cookie
#      confirmation-service:
#          service-id: confirmation-service
#          path: /confirmation/**
#          url: ${CONFIRMATION_SERVICE_URI:http://localhost:8050}
#          stripPrefix: false
#          sensitiveHeaders: Cookie,Set-Cookie

server:
  port: 4000
