<<<<<<< HEAD
spring:
  datasource:
    # url: jdbc:mysql://127.0.0.1:3306/tasirmisin
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:cloudoeedb}?serverTimezone=UTC
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:123456Aa}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
=======
keycloak:
  resource: maindata-service
  credentials: 
    secret: 9cb2426a-4f3f-4c7b-bd5c-3f776efef3bb
#  use-resource-role-mappings: true
>>>>>>> keycloak_branch

server:
  port: 8090
