pipeline {

    agent any

    stages {

        stage('Build') {
            steps {
                sh '''
                    ./nginx-certbot/init-letsencrypt.sh
                '''
            }
        }
    }
}
