spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/{profile}
  profiles:
     active: native
  security:
    user:
      password: 123456
      
server:
  port: 8888
